### ISSUE TITLE
Error formatting "folded" lines

### ISSUE THREAD

**Issue by calvinmclean** [calvinmclean/ansible-formatter#1]
[Yaml documentation for this syntax](http://yaml.org/spec/1.2/spec.html#id2796251)

### Example:
Before formatting:
```yaml
- name: ensure local files directory exists
  local_action: >
      file path={{ role_path }}/files state=directory mode=0755
```

After formatting:
```yaml
- name: ensure local files directory exists
  local_action: >
      file path={{ role_path }}/files state=directory mode=0755
:
```
